//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2017/2/28 11:08:53]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace tabtool
{

    public class tbsAchiveItem
    {
        public int id;
        public string name;
        public tbsIdCount test1;
        public List<int> test2;
        public List<tbsKeyValue> test3;
    }

    public class cfgAchiveTable : TableManager<tbsAchiveItem, cfgAchiveTable>
    {
        public override bool Load()
        {
            TableReader tr = new TableReader();
            DataReader dr = new DataReader();
            DataTable dt = tr.ReadFile(MyConfig.WorkDir+"Achive.txt");

            foreach(DataRow row in dt.Rows)
            {
                var item = new tbsAchiveItem();
                  item.id = dr.GetInt(row["id"].ToString());
                  item.name = (row["name"].ToString());
                  item.test1 = dr.GetObject<tbsIdCount>(row["test1"].ToString());
                  item.test2 = dr.GetIntList(row["test2"].ToString());
                  item.test3 = dr.GetObjectList<tbsKeyValue>(row["test3"].ToString());
                  m_Items[item.id] = item;
            }
            return true;
        }
    }

    public class TableConfig : SingletonTable<TableConfig>
    {
        public bool LoadTableConfig()
        {
            if (!cfgAchiveTable.Instance.Load()) return false;
            return true;
        }
    }
}
