//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2017/2/28 11:08:53]
#pragma once
# include "tabletool/myconfig.h"
# include "tabletool/singleton.h"
# include "tabletool/readtablefield.h"
# include "tablestruct.h"


bool LoadTableConfig();


struct tbsAchiveItem {
  int id;
  int line;
  tbsIdCount test1;
  vector<int> test2;
  vector<tbsKeyValue> test3;
};

class cfgAchiveTable:public IConfigTable<tbsAchiveItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "Achive.txt";
        return f;
    }

};

